issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - dupl

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
  - bodyclose
  - contextcheck
  - deadcode
  - depguard
  - dogsled
  - dupl
  - errcheck
  - exportloopref
  - exhaustive
  - goconst
  - gocyclo
  - gofmt
  - goimports
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - noctx
  - nolintlint
  - revive
  - rowserrcheck
  - staticcheck
  - structcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
