issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - dupl
    - linters:
        - revive
        - stylecheck
      text: dot imports
      source: gomega
    - linters:
        - revive
        - stylecheck
      text: dot imports
      source: ginkgo

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
  - bodyclose
  - contextcheck
  - dogsled
  - dupl
  - errcheck
  - exportloopref
  - exhaustive
  - goconst
  - gocyclo
  - gofmt
  - goimports
  - goprintffuncname
  - gosimple
  - govet
  - ineffassign
  - misspell
  - nakedret
  - noctx
  - nolintlint
  - revive
  - rowserrcheck
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
