repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.5.0
  hooks:
  - id: commitlint
    stages: [commit-msg]
- repo: https://github.com/golangci/golangci-lint
  rev: v1.51.2
  hooks:
  - id: golangci-lint
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
  - id: go-mod-tidy
- repo: https://github.com/bufbuild/buf
  rev: v1.17.0
  hooks:
  - id: buf-lint
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.7
  hooks:
  - id: clang-format
    types_or: [proto]
- repo: https://github.com/adamchainz/pre-commit-dprint
  rev: v0.36.0
  hooks:
  - id: dprint
    types_or:
    - markdown
